apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  #lb_auth_issuer_uri: http://host.docker.internal:9000
  #lb_usuarios_uri: http://host.docker.internal:8001
  #lb_auth_issuer_uri: http://msvc-auth:9000
  #lb_usuarios_uri: http://msvc-usuarios:8001
  lb_auth_issuer_uri: http://172.29.154.84:31096
  lb_usuarios_uri: http://172.29.154.84:30239
  port: "8001"
  db_host: "mysql8:3306"
  database: msvc_usuarios
  username: root
  password: sasa
  curso_url: "msvc-cursos:8002"
  config.texto: Configurando ambiente por defecto
  application.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de producción
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
  username: postgres
  password: sasa
  usuario_url: msvc-usuarios:8001