apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - name: postgres14
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: sasa
            - name: POSTGRES_DB
              value: msvc_cursos
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
#          hostPath:
#            path: /var/lib/postgresql/data
#            type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: pvc-postgres