version: "3.9"
services:
  mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      #- MYSQL_ROOT_PASSWORD=sasa
      MYSQL_ROOT_PASSWORD: sasa
      #- MYSQL_DATABASE=msvc_usuarios
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    image: usuarios:latest
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always


  msvc-cursos:
    image: cursos:latest
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:
  data-mysql:
  data-postgres:

networks:
  spring: