apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  capacity:
    storage: 2G
  volumeMode: Filesystem
  #usar el nombre resultante del comando kubectl get sc
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate