apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  volumeName: pv-mysql
  accessModes:
    #multinodo amazon eks
#    - ReadWriteMany
    - ReadWriteOnce
#  storageClassName: ""
  storageClassName: standard
  resources:
    requests:
      storage: 2G