spring:
  security:
    oauth2:
      client:
        registration:
          msvc-usuarios-client:
            provider: spring
            client-id: usuarios-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8001/authorized"
            scope: read
            client-name: msvc-usuarios-client
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000